// Cartes multi-ères : les affaires courantes du royaume et ses visiteurs
// récurrents. Elles alimentent le tirage de la Roche jusqu'à la Chute
// (Avalon, épilogue mythique, garde son paquet propre).

const ERAS_VIVANTES = ['roche', 'camelot', 'graal', 'chute'];

export const common = [
  {
    id: 'common.saxons.raid',
    era: ERAS_VIVANTES,
    speaker: 'Gauvain',
    text: "Des drakkars saxons pillent la côte est, Sire. Lèverons-nous l'ost, ou leur paierons-nous le prix de la paix ?",
    requires: { noneFlags: ['epreuve.bataille.saxonne'] },
    left: {
      label: "Lever l'ost",
      combat: 'bataille.saxonne',
      flags: ['epreuve.bataille.saxonne'],
    },
    right: {
      label: 'Payer le tribut',
      effects: { couronne: +4, chevalerie: -7 },
    },
    weight: 1,
  },
  {
    id: 'common.eveque.dime',
    era: ERAS_VIVANTES,
    speaker: "L'Évêque",
    text: "Dieu a béni tes récoltes, mon roi. Il serait juste que Son Église en reçoive la dîme… doublée, cette année.",
    left: {
      label: 'Doubler la dîme',
      effects: { foi: +8, couronne: -6 },
      flags: [['piete', 1]],
    },
    right: {
      label: 'Refuser',
      effects: { couronne: +5, foi: -8 },
    },
    weight: 1,
  },
  {
    id: 'common.merlin.vision',
    era: ERAS_VIVANTES,
    speaker: 'Merlin',
    text: "Les étoiles ont parlé cette nuit. Veux-tu entendre ce qu'elles disent de ton règne — même si cela te déplaît ?",
    left: {
      label: 'Écouter les astres',
      effects: { magie: +7, foi: -4 },
    },
    right: {
      label: 'Je ne veux pas savoir',
      effects: { foi: +4, magie: -6 },
    },
    weight: 1,
  },
  {
    id: 'common.morgane.philtre',
    era: ERAS_VIVANTES,
    requires: { noneFlags: ['lignee.morgane'] },
    speaker: 'Morgane',
    text: "Un philtre pour lier tes chevaliers à toi par serment enchanté. Un cadeau de ta chère sœur… sans arrière-pensée, bien sûr.",
    left: {
      label: 'Accepter le philtre',
      effects: { magie: +8, chevalerie: -4 },
    },
    right: {
      label: 'Se méfier de Morgane',
      effects: { chevalerie: +4, magie: -7 },
    },
    weight: 1,
  },
  {
    id: 'common.proces.guerisseuse',
    era: ERAS_VIVANTES,
    speaker: "L'Évêque",
    text: "Une guérisseuse des bois soigne par les herbes et les murmures. Le peuple l'aime ; l'Église la dit sorcière. Ton verdict ?",
    left: {
      label: 'Le bûcher',
      effects: { foi: +9, magie: -9 },
      flags: [['cruaute', 1]],
    },
    right: {
      label: 'La gracier',
      effects: { magie: +8, foi: -8 },
    },
    weight: 1,
  },
  {
    id: 'common.keu.banquet',
    era: ERAS_VIVANTES,
    speaker: 'Keu',
    text: "Les barons attendent le banquet d'usage, Sire. Les caves sont basses, mais leur patience l'est davantage.",
    left: {
      label: 'Banquet fastueux',
      effects: { couronne: +6, foi: -3 },
    },
    right: {
      label: 'Table frugale',
      effects: { foi: +4, couronne: -5 },
    },
    weight: 1,
  },
  {
    id: 'common.gauvain.duel',
    era: ERAS_VIVANTES,
    speaker: 'Gauvain',
    text: "Un chevalier a insulté mon sang, Sire. Accorde-moi le duel — ou je devrai l'exiger moins poliment.",
    left: {
      label: 'Accorder le duel',
      effects: { chevalerie: +6, couronne: -3 },
    },
    right: {
      label: 'Interdire',
      effects: { couronne: +3, chevalerie: -5 },
    },
    weight: 1,
  },
  {
    id: 'common.barde.chanson',
    era: ERAS_VIVANTES,
    speaker: 'Un barde',
    text: "J'ai composé une geste sur ton règne, Sire. Moyennant pension, elle courra toutes les tavernes de Logres.",
    left: {
      label: 'Payer le barde',
      effects: { couronne: +5, foi: -3 },
    },
    right: {
      label: 'La gloire suffira',
      effects: { foi: +3, couronne: -4 },
    },
    weight: 1,
  },
  {
    id: 'common.paysans.pont',
    era: ERAS_VIVANTES,
    speaker: 'Un paysan',
    text: "Le pont sur la Saverne s'est effondré, Sire. Sans lui, plus de marché — et l'on dit qu'un troll s'est installé dessous.",
    left: {
      label: 'Rebâtir le pont',
      effects: { couronne: +6, chevalerie: -3 },
    },
    right: {
      label: "Qu'ils contournent",
      effects: { couronne: -6, magie: +4 },
    },
    weight: 1,
  },
  {
    id: 'common.dame.lac.entretien',
    era: ERAS_VIVANTES,
    speaker: 'La Dame du Lac',
    text: "Excalibur boit ta gloire, roi de Logres. N'oublie pas de qui elle vient — Avalon attend une offrande.",
    requires: { allFlags: ['relique.excalibur'] },
    left: {
      label: "Honorer Avalon",
      effects: { magie: +6, foi: -5 },
    },
    right: {
      label: "L'épée est à moi",
      effects: { couronne: +4, magie: -6 },
    },
    weight: 1,
  },
  {
    id: 'common.justice.appel',
    era: ERAS_VIVANTES,
    speaker: 'Un paysan',
    text: "Le baron m'a jugé et le baron m'a condamné — pour le champ que le baron convoite, Sire. Il paraît que ta justice est au-dessus de la sienne. On vérifie ?",
    left: { label: 'Casser le jugement', effects: { couronne: +6, chevalerie: -4 } },
    right: { label: 'Le baron est chez lui', effects: { chevalerie: +4, couronne: -5 } },
    weight: 1,
  },
  {
    id: 'common.impot.guerre',
    era: ERAS_VIVANTES,
    speaker: 'Un conseiller',
    text: "Un impôt de guerre remplirait les coffres, Sire. Le peuple grognera, l'Église tonnera — mais les soldats mangent mal les bénédictions.",
    left: { label: "Lever l'impôt", effects: { couronne: +7, foi: -5 } },
    right: { label: 'Épargner le peuple', effects: { foi: +5, couronne: -6 } },
    weight: 1,
  },
  {
    id: 'common.eveque.miracle',
    era: ERAS_VIVANTES,
    speaker: "L'Évêque",
    text: "Une source a jailli sous la cathédrale, Sire — miracle, à n'en point douter. Viens l'endosser devant le peuple, avant que d'autres n'y voient de la magie.",
    left: { label: 'Endosser le miracle', effects: { foi: +7, magie: -6 } },
    right: { label: "C'est de la vieille magie", effects: { magie: +6, foi: -6 } },
    weight: 1,
  },
  {
    id: 'common.morgane.conseil',
    era: ERAS_VIVANTES,
    requires: { noneFlags: ['lignee.morgane'] },
    speaker: 'Morgane',
    text: "Un conseil, frère, gratuit : méfie-toi de ton nouvel ami qui prie si fort. Ce conseil est trop juste pour être honnête — c'est bien pour ça qu'il est bon.",
    left: { label: 'Suivre le conseil', effects: { magie: +6, foi: -6 } },
    right: { label: "Se méfier d'elle", effects: { foi: +5, magie: -5 } },
    weight: 1,
  },
  {
    id: 'common.gauvain.honneur',
    era: ERAS_VIVANTES,
    speaker: 'Gauvain',
    text: "On a ri de la Table à la cour d'Orcanie, Sire. Un affront lavé vaut mieux qu'un affront discuté. Laisse-moi partir.",
    left: { label: "Laver l'affront", effects: { chevalerie: +6, couronne: -4 } },
    right: { label: 'Un rire ne tue pas', effects: { couronne: +4, chevalerie: -5 } },
    weight: 1,
  },
  {
    id: 'common.saxons.commerce',
    era: ERAS_VIVANTES,
    speaker: 'Un marchand',
    text: "Les Saxons ont de l'ambre et du fer, Sire, et nos guerres coûtent plus qu'elles ne rapportent. Ouvrons-leur un marché — les épées, on verra plus tard.",
    left: { label: 'Ouvrir le marché', effects: { couronne: +6, chevalerie: -5 } },
    right: { label: 'Pas de troc avec eux', effects: { chevalerie: +5, couronne: -4 } },
    weight: 1,
  },
  {
    id: 'common.merlin.augure',
    era: ERAS_VIVANTES,
    speaker: 'Merlin',
    text: "Prête-moi un taureau blanc, Sire. Ses entrailles diront la saison à venir — l'Évêque hurlera, mais l'Évêque ne prédit rien, lui.",
    left: { label: 'Lire les entrailles', effects: { magie: +7, foi: -6 } },
    right: { label: 'Épargne le taureau', effects: { foi: +5, magie: -5 } },
    weight: 1,
  },
  {
    id: 'common.baron.mariage',
    era: ERAS_VIVANTES,
    speaker: 'Un baron',
    text: "Ma fille, son fils : deux fiefs unis, Sire — ou deux fiefs en guerre si tu bénis l'autre parti. Ta parole fera l'un ou l'autre.",
    left: { label: "Bénir l'union", effects: { couronne: +5, chevalerie: -3 } },
    right: { label: 'Que la lice décide', effects: { chevalerie: +5, couronne: -4 } },
    weight: 1,
  },
  {
    id: 'common.paysan.doleances',
    era: ERAS_VIVANTES,
    speaker: 'Un paysan',
    text: "Nous voilà, Sire : le sel trop cher, la corvée trop longue, et le bailli trop gras. On nous a dit que le roi écoute. C'est un début.",
    left: { label: 'Alléger la corvée', effects: { foi: +5, couronne: -5 } },
    right: { label: 'Renvoyer la délégation', effects: { couronne: +5, foi: -5 } },
    weight: 1,
  },
  {
    id: 'common.marchand.pret',
    era: ERAS_VIVANTES,
    speaker: 'Un marchand',
    text: "Je prête gros, Sire, et sans intérêt — contre le monopole du sel et une pincée de privilèges. L'usure est un péché ; les affaires, non.",
    left: { label: 'Accepter le prêt', effects: { couronne: +7, foi: -6 } },
    right: { label: "Refuser l'usurier", effects: { foi: +5, couronne: -5 } },
    weight: 1,
  },
  {
    id: 'common.relique.pretre',
    era: ERAS_VIVANTES,
    speaker: "L'Évêque",
    text: "Nous avons saisi un grimoire qui sent le soufre, Sire. Le bûcher l'attend — à moins que ton mage n'y tienne, ce qui en dirait long.",
    left: { label: 'Brûler le grimoire', effects: { foi: +6, magie: -7 } },
    right: { label: 'Le confier au mage', effects: { magie: +6, foi: -6 } },
    weight: 1,
  },
  {
    id: 'common.heraut.defi',
    era: ERAS_VIVANTES,
    speaker: 'Un héraut',
    text: "Le roi d'Outre-Humber te défie en champ clos, Sire — toi ou ton champion. Refuser se peut, mais ça se chante mal.",
    requires: { noneFlags: ['epreuve.champ.clos'] },
    left: { label: 'Relever le défi', combat: 'champ.clos', flags: ['epreuve.champ.clos'] },
    right: { label: "L'ignorer de haut", effects: { couronne: +4, chevalerie: -6 } },
    weight: 1,
  },
  {
    id: 'common.dame.lac.offrande',
    era: ERAS_VIVANTES,
    speaker: 'La Dame du Lac',
    text: "Le lac a soif d'or et d'égards, roi de Logres. Jette-lui un anneau — les dettes d'Avalon se paient toujours, tôt ou tard.",
    left: { label: "Jeter l'or au lac", effects: { magie: +6, couronne: -5 } },
    right: { label: "L'or reste au trésor", effects: { couronne: +5, magie: -6 } },
    weight: 1,
  },
  // ---- Échos des épreuves perdues : les défaites s'installent ----
  {
    id: 'common.saxons.hivernage',
    era: ERAS_VIVANTES,
    speaker: 'Un émissaire saxon',
    text: "Nos maisons sur ta côte ont passé l'hiver, Sire. Nous voilà presque voisins — le tribut de printemps, maintenant. Entre voisins.",
    requires: { allFlags: ['saxons.installes'] },
    left: { label: 'Payer, encore', effects: { couronne: +4, chevalerie: -6 } },
    right: { label: 'Brûler leurs maisons', effects: { chevalerie: +6, couronne: -5 } },
    weight: 2,
  },
  {
    id: 'common.barde.noir',
    era: ERAS_VIVANTES,
    speaker: 'Un barde',
    text: "La chanson du Chevalier Noir fait un triomphe, Sire — surtout le couplet où ton champion mord la poussière. On me la réclame jusque dans ta salle.",
    unique: true,
    requires: { allFlags: ['tournoi.perdu'] },
    left: { label: 'Rire avec la salle', effects: { couronne: +4, chevalerie: -4 } },
    right: { label: 'Bannir la chanson', effects: { chevalerie: +3, couronne: -4 } },
    weight: 2,
  },
  {
    id: 'common.outre.humber.revanche',
    era: ERAS_VIVANTES,
    speaker: 'Un héraut',
    text: "Le roi d'Outre-Humber fait broder ta défaite sur ses bannières, Sire. Il accepterait une revanche — par pure bonté, précise-t-il.",
    unique: true,
    requires: { allFlags: ['champ.clos.perdu'] },
    left: {
      label: 'La revanche',
      combat: 'champ.clos',
      flags: ['epreuve.champ.clos.revanche'],
    },
    right: {
      label: 'Laisser broder',
      effects: { couronne: +3, chevalerie: -5 },
    },
    weight: 2,
  },
  // ---- Réputation : les choix répétés finissent par avoir un nom ----
  {
    id: 'common.roi.craint',
    era: ERAS_VIVANTES,
    speaker: 'Un conseiller',
    text: "Le peuple ne t'appelle plus « le jeune roi », Sire. Le nouveau nom est moins flatteur — mais il fait baisser les yeux, et les impôts rentrent.",
    unique: true,
    requires: { counts: { cruaute: 3 } },
    left: { label: 'La peur est un outil', effects: { couronne: +6, foi: -5 } },
    right: { label: 'Adoucir le règne', effects: { foi: +5, couronne: -4 } },
    weight: 3,
  },
  {
    id: 'common.roi.beni',
    era: ERAS_VIVANTES,
    speaker: 'Un pèlerin',
    text: "On vient de trois royaumes pour toucher ton ombre, Sire — on te dit béni. J'ai fait la route moi-même, au cas où.",
    unique: true,
    requires: { counts: { piete: 3 } },
    left: { label: 'Bénir les pèlerins', effects: { foi: +6, couronne: -4 } },
    right: { label: "Je ne suis qu'un roi", effects: { couronne: +4, foi: -4 } },
    weight: 3,
  },
  {
    id: 'common.conseiller.reforme',
    era: ERAS_VIVANTES,
    speaker: 'Un conseiller',
    text: "Une loi égale pour le baron et le manant, Sire. Les barons crieront, l'histoire applaudira. L'histoire vote peu, hélas.",
    left: { label: 'Réformer les lois', effects: { couronne: +6, foi: -4 } },
    right: { label: 'Ne rien changer', effects: { foi: +4, couronne: -5 } },
    weight: 1,
  },
];
