// Ères 3-5 — Graal, Chute, Avalon. Les chaînes posées plus tôt éclatent ici.

export const graal = [
  {
    id: 'graal.perceval.retour',
    era: 'graal',
    speaker: 'Perceval',
    text: "J'ai vu le Graal, mais mes mains l'ont laissé fuir. Dois-je repartir, au risque de vider ta Table ?",
    unique: true,
    requires: { anyFlags: ['graal.quete'] },
    left: {
      label: 'Repartir',
      effects: { foi: +12, chevalerie: -10 },
    },
    right: {
      label: 'Rentre à Camelot',
      effects: { chevalerie: +8, foi: -8 },
    },
    weight: 2,
  },
  {
    id: 'graal.filler.pelerins',
    era: 'graal',
    filler: true,
    speaker: "L'Évêque",
    text: "Des pèlerins affluent vers Logres. Ouvriras-tu les greniers royaux pour les nourrir ?",
    left: { label: 'Nourrir les pèlerins', effects: { foi: +7, couronne: -5 } },
    right: { label: 'Refermer les greniers', effects: { couronne: +5, foi: -6 } },
    weight: 1,
  },
  {
    id: 'graal.filler.eremite',
    era: 'graal',
    filler: true,
    speaker: 'Un ermite',
    text: "L'ancienne magie s'efface des bois, dit-on. Feras-tu protéger les cercles de pierres ?",
    left: { label: 'Protéger les pierres', effects: { magie: +7, foi: -5 } },
    right: { label: 'Les laisser tomber', effects: { foi: +5, magie: -6 } },
    weight: 1,
  },
  {
    id: 'graal.galaad.siege',
    era: 'graal',
    speaker: 'Galaad',
    text: "Le Siège Périlleux m'attend, dit-on — la place qui foudroie les indignes. Me laisseras-tu m'y asseoir, Sire ?",
    unique: true,
    requires: { allFlags: ['graal.quete'] },
    left: {
      label: "Qu'il s'asseye",
      effects: { foi: +8, chevalerie: +4, magie: -6 },
    },
    right: {
      label: 'Trop de risque',
      effects: { magie: +4, foi: -6 },
    },
    weight: 2,
  },
  {
    id: 'graal.table.vide',
    era: 'graal',
    speaker: 'Keu',
    text: "La Table sonne creux, Sire : tes chevaliers courent après une coupe. Rappelleras-tu ceux qui restent en vie ?",
    requires: { allFlags: ['graal.quete'] },
    left: {
      label: 'Rappeler les survivants',
      effects: { chevalerie: +6, foi: -7 },
    },
    right: {
      label: 'La quête est sacrée',
      effects: { foi: +7, chevalerie: -6 },
    },
    weight: 1,
  },
  {
    id: 'graal.fausse.relique',
    era: 'graal',
    speaker: 'Un marchand',
    text: "Le Graal, Sire, le vrai ! Trouvé à Jérusalem, ou pas loin. Pour toi : prix d'ami. Les pèlerins paieraient cher pour le voir.",
    unique: true,
    left: {
      label: "L'acheter et l'exposer",
      effects: { couronne: +6, foi: -7 },
    },
    right: {
      label: 'Chasser ce filou',
      effects: { foi: +5, couronne: -3 },
    },
    weight: 1,
  },
  {
    id: 'graal.sans.merlin',
    era: 'graal',
    speaker: 'Un conseiller',
    text: "Depuis que Merlin a suivi sa dame au fond des bois, nul ne lit plus les présages. La cour marche à l'aveugle, Sire.",
    requires: { allFlags: ['merlin.parti'] },
    left: {
      label: 'Chercher un autre mage',
      effects: { magie: +6, foi: -6 },
    },
    right: {
      label: 'Dieu nous guidera',
      effects: { foi: +6, magie: -5 },
    },
    weight: 1,
  },
  {
    id: 'graal.morgane.convoitise',
    era: 'graal',
    speaker: 'Morgane',
    text: "Cette coupe que cherchent tes chevaliers n'est pas chrétienne, frère. Elle est d'Avalon — et Avalon la réclame.",
    unique: true,
    requires: { allFlags: ['morgane.cour'] },
    left: {
      label: 'Le Graal ira à Avalon',
      effects: { magie: +8, foi: -8 },
    },
    right: {
      label: 'Il ira à Dieu',
      effects: { foi: +7, magie: -8 },
    },
    weight: 2,
  },
  {
    id: 'graal.mordred.chevalier',
    era: 'graal',
    speaker: 'Mordred',
    text: "Père — ou « mon roi », si tu préfères. J'ai grandi, et je manie l'épée mieux que tes vieux barons. Donne-moi une place à ta Table… que je serve, ou que je m'ennuie.",
    unique: true,
    requires: { anyFlags: ['mordred.eleve', 'mordred.ecarte'] },
    left: {
      label: 'Le distinguer',
      effects: { chevalerie: +6, couronne: -4 },
      flags: ['mordred.ambitieux'],
    },
    right: {
      label: 'Le tenir en lisière',
      effects: { couronne: +5, chevalerie: -5, magie: -3 },
    },
    weight: 2,
  },
  {
    id: 'graal.lancelot.tension',
    era: 'graal',
    speaker: 'Keu',
    text: "Lancelot est rentré de la quête plus glorieux que jamais, et la reine sourit plus qu'il ne sied, Sire. La cour a des yeux.",
    requires: { allFlags: ['lancelot.cour'], noneFlags: ['lancelot.banni'] },
    left: {
      label: 'Les faire surveiller',
      effects: { couronne: +4, chevalerie: -4 },
    },
    right: {
      label: 'Leur faire confiance',
      effects: { chevalerie: +4, foi: -4 },
    },
    weight: 1,
  },
  {
    id: 'graal.exode',
    era: 'graal',
    speaker: 'Un héraut',
    text: "La moitié de la Table a sellé ses chevaux pour la coupe, Sire. Béniras-tu ce grand départ — ou rappelleras-tu tes chevaliers avant que Camelot ne sonne creux ?",
    unique: true,
    requires: { allFlags: ['graal.quete'] },
    left: {
      label: 'Bénir le départ',
      effects: { foi: +10, chevalerie: -12 },
      flags: ['graal.exode'],
    },
    right: {
      label: 'Retenir la Table',
      effects: { chevalerie: +8, foi: -8 },
    },
    weight: 3,
  },
  {
    id: 'graal.roi.pecheur',
    era: 'graal',
    speaker: 'Un ermite',
    text: "Au château du Graal règne un roi blessé qui ne meurt ni ne guérit, et sa terre pourrit avec lui. Ton chevalier doit poser LA question, Sire — mais laquelle ?",
    unique: true,
    requires: { allFlags: ['graal.quete'] },
    left: {
      label: '« Qui sert-on avec le Graal ? »',
      effects: { foi: +8, magie: +2, couronne: -4 },
    },
    right: {
      label: '« Où est caché le trésor ? »',
      effects: { couronne: +5, foi: -7 },
    },
    weight: 1,
  },
  {
    id: 'graal.galaad.atteint',
    era: ['graal', 'chute'],
    speaker: 'Galaad',
    text: "Sire, je l'ai vu — le Graal, à visage découvert. Ma quête s'achève, et moi avec elle : je monte vers la lumière. Que dira Camelot de ce jour ?",
    unique: true,
    requires: { allFlags: ['graal.quete', 'graal.exode'] },
    left: {
      label: 'Pleurer un saint',
      effects: { foi: +12, chevalerie: -6 },
      flags: ['graal.atteint'],
    },
    right: {
      label: 'Maudire cette quête',
      effects: { chevalerie: +6, foi: -10 },
      flags: ['graal.echoue'],
    },
    weight: 2,
  },
  {
    id: 'graal.excalibur.doute',
    era: 'graal',
    speaker: "L'Évêque",
    text: "Cette épée sort d'un lac païen, Sire, non de l'autel de Dieu. Un roi chrétien devrait-il la ceindre encore, en ces temps de sainte quête ?",
    unique: true,
    requires: { allFlags: ['relique.excalibur'], noneFlags: ['excalibur.rendue'] },
    left: {
      label: 'La rendre au lac',
      effects: { foi: +8, chevalerie: -6 },
      flags: ['excalibur.rendue'],
    },
    right: {
      label: 'Elle est à Logres',
      effects: { chevalerie: +6, foi: -6 },
    },
    weight: 1,
  },
  // ---- Standalone : mysticisme, Table qui se vide, ferveur et filous ----
  {
    id: 'graal.visions.foule',
    era: 'graal',
    speaker: 'Un paysan',
    text: "Aux champs de l'ouest, des anges moissonnent avec nous — enfin, c'est ce qu'on dit, Sire. Le village entier prie au lieu de faucher. Viendras-tu bénir le miracle, ou remettre tout le monde au travail ?",
    left: { label: 'Bénir le miracle', effects: { foi: +7, couronne: -4 } },
    right: { label: 'Au travail !', effects: { couronne: +5, foi: -6 } },
    weight: 1,
  },
  {
    id: 'graal.ermite.jeune',
    era: 'graal',
    speaker: 'Un ermite',
    text: "Le Graal ne se montre qu'aux ventres vides, Sire. Que la cour jeûne quarante jours — toi le premier, naturellement.",
    left: { label: 'Que la cour jeûne', effects: { foi: +8, couronne: -5 } },
    right: { label: 'Un roi doit dîner', effects: { couronne: +4, foi: -6 } },
    weight: 1,
  },
  {
    id: 'graal.morgane.offre',
    era: 'graal',
    speaker: 'Morgane',
    text: "Tes chevaliers cherchent la coupe avec des prières. Moi, je la trouverais en une lune — à ma façon. Tu n'aurais qu'à ne pas demander comment.",
    unique: true,
    left: { label: 'Accepter son aide', effects: { magie: +7, foi: -7 } },
    right: { label: 'Pas de sorcellerie', effects: { foi: +6, magie: -6 } },
    weight: 1,
  },
  {
    id: 'graal.faux.prophete',
    era: 'graal',
    speaker: 'Un conseiller',
    text: "Un prêcheur en haillons ameute les places : « le Graal fuit les rois indignes ! » La foule l'écoute plus que tes hérauts, Sire.",
    left: { label: 'Le faire taire', effects: { couronne: +5, foi: -6 } },
    right: { label: 'Laisser Dieu trancher', effects: { foi: +5, couronne: -5 } },
    weight: 1,
  },
  {
    id: 'graal.pierres.effacent',
    era: 'graal',
    speaker: 'La Dame du Lac',
    text: "Les cercles de pierres se taisent un à un, roi de Logres. Ta sainte quête assèche la vieille magie. Porteras-tu des offrandes aux pierres — ou les laisseras-tu mourir ?",
    left: { label: 'Raviver les pierres', effects: { magie: +7, foi: -6 } },
    right: { label: 'Leur temps est passé', effects: { foi: +6, magie: -7 } },
    weight: 1,
  },
  {
    id: 'graal.chevaliers.perdus',
    era: 'graal',
    speaker: 'Keu',
    text: "Trois chevaliers manquent à l'appel depuis l'automne, Sire. Une battue coûterait cher — mais la Table n'abandonne pas les siens. En principe.",
    left: { label: 'Envoyer une battue', effects: { chevalerie: +6, couronne: -5 } },
    right: { label: 'La quête les a pris', effects: { couronne: +4, chevalerie: -6 } },
    weight: 1,
  },
  {
    id: 'graal.abbaye.don',
    era: 'graal',
    speaker: 'Un moine',
    text: "Notre abbaye garde une écharde de la Vraie Croix, Sire. Pour l'abriter dignement, il nous faudrait… tes terres du val. Dieu compte, tu sais.",
    left: { label: 'Donner les terres', effects: { foi: +7, couronne: -6 } },
    right: { label: 'Dieu se contentera', effects: { couronne: +5, foi: -5 } },
    weight: 1,
  },
  {
    id: 'graal.dame.lac.avertit',
    era: 'graal',
    speaker: 'La Dame du Lac',
    text: "Cette quête chrétienne piétine mes rives, roi de Logres. Avalon t'a donné une épée ; elle sait reprendre. Choisis mieux tes coupes.",
    unique: true,
    left: { label: 'Apaiser Avalon', effects: { magie: +7, foi: -7 } },
    right: { label: 'La quête est sainte', effects: { foi: +7, magie: -7 } },
    weight: 1,
  },
  {
    id: 'graal.pelerins.affluence',
    era: 'graal',
    speaker: 'Un marchand',
    text: "Ces pèlerins encombrent les routes, Sire, mais leurs bourses tintent. Taxons les auberges — pour leur salut, bien entendu.",
    left: { label: 'Taxer les auberges', effects: { couronne: +6, foi: -5 } },
    right: { label: 'On ne taxe pas la foi', effects: { foi: +5, couronne: -4 } },
    weight: 1,
  },
  {
    id: 'graal.moine.copie',
    era: 'graal',
    speaker: 'Un moine',
    text: "Laisse-moi consigner tes lois dans un grand livre enluminé, Sire. Les siècles te liront — si tu paies l'encre et vingt copistes.",
    left: { label: 'Payer les copistes', effects: { foi: +6, couronne: -4 } },
    right: { label: 'La parole suffit', effects: { couronne: +3, foi: -4 } },
    weight: 1,
  },
  {
    id: 'graal.marchand.indulgences',
    era: 'graal',
    speaker: 'Un marchand',
    text: "Je vends des pardons scellés « au nom du roi très chrétien ». Ça se vend fort bien. Une part pour la couronne, et personne n'en saura rien ?",
    left: { label: 'Prendre la part', effects: { couronne: +6, foi: -8 } },
    right: { label: 'Au pilori', effects: { foi: +6, couronne: -3 } },
    weight: 1,
  },
  {
    id: 'graal.paien.retour',
    era: 'graal',
    speaker: "L'Évêque",
    text: "Pendant que tes chevaliers cherchent Dieu au loin, Sire, les campagnes redansent autour des vieilles idoles. Il faut sévir — ou avouer que la foi s'ennuie.",
    left: { label: 'Sévir', effects: { foi: +6, magie: -7 } },
    right: { label: 'Laisser danser', effects: { magie: +6, foi: -6 } },
    weight: 1,
  },
  {
    id: 'graal.keu.intendance',
    era: 'graal',
    speaker: 'Keu',
    text: "La moitié des chambres sont vides et je nourris encore cent écuyers, Sire. Réduisons le train royal — ou qu'on m'explique à quoi servent des palefreniers sans chevaux.",
    left: { label: 'Réduire le train', effects: { couronne: +5, chevalerie: -4 } },
    right: { label: 'Tenir le rang', effects: { chevalerie: +4, couronne: -5 } },
    weight: 1,
  },
  {
    id: 'graal.jeune.roi.voisin',
    era: 'graal',
    speaker: 'Un héraut',
    text: "Le roi de Cornouailles grignote tes marches, Sire — il dit que ta Table est vide et tes frontières aussi. Il n'a pas tout à fait tort.",
    left: { label: 'Montrer les dents', effects: { chevalerie: +6, couronne: -4 } },
    right: { label: 'Négocier un tribut', effects: { couronne: +4, chevalerie: -6 } },
    weight: 1,
  },
];

export const chute = [
  // ---- Éclatement de la chaîne Mordred, posée à l'ère de la Roche ----
  {
    id: 'chute.mordred.revele',
    era: 'chute',
    speaker: 'Mordred',
    text: "Père. Oui — père. Le fils que Morgane t'a donné, celui que tu as élevé ou banni, réclame aujourd'hui sa part de Logres. Me nommeras-tu héritier ?",
    unique: true,
    requires: { allFlags: ['mordred.concu'] },
    left: {
      label: 'Le reconnaître',
      effects: { couronne: +6, chevalerie: -12 },
      flags: ['mordred.heritier'],
    },
    right: {
      label: 'Le renier',
      effects: { chevalerie: +4, magie: -10 },
      flags: ['mordred.ennemi'],
    },
    weight: 3,
  },
  {
    id: 'chute.mordred.guerre',
    era: 'chute',
    speaker: 'Gauvain',
    text: "Mordred lève une armée contre toi ! Marcherons-nous sur lui à Camlann ?",
    unique: true,
    requires: { anyFlags: ['mordred.ennemi'] },
    left: {
      label: 'Marcher sur Camlann',
      effects: { chevalerie: -14, couronne: +6 },
      flags: ['camlann'],
    },
    right: {
      label: 'Négocier',
      effects: { couronne: -10, foi: +4 },
    },
    weight: 3,
  },
  {
    id: 'chute.affaire.mordred',
    era: 'chute',
    speaker: 'Mordred',
    text: "J'ai des lettres, père. De la reine, à Lancelot. Faut-il que toute la cour les lise — ou préfères-tu, encore une fois, ne rien voir ?",
    unique: true,
    requires: {
      allFlags: ['affaire.tue'],
      anyFlags: ['mordred.eleve', 'mordred.ecarte', 'mordred.ambitieux'],
    },
    left: {
      label: 'Que tout éclate',
      effects: { couronne: -6, chevalerie: -8 },
      flags: ['affaire.exposee', 'lancelot.banni'],
    },
    right: {
      label: 'Étouffer encore',
      effects: { couronne: +5, foi: -8, magie: -4 },
    },
    weight: 3,
  },
  {
    id: 'chute.filler.desertion',
    era: 'chute',
    filler: true,
    speaker: 'Keu',
    text: "Des chevaliers désertent la Table, découragés. Sévir contre les traîtres ?",
    left: { label: 'Sévir', effects: { couronne: +5, chevalerie: -6 } },
    right: { label: 'Leur pardonner', effects: { chevalerie: +5, couronne: -5 } },
    weight: 1,
  },
  {
    id: 'chute.filler.presage',
    era: 'chute',
    filler: true,
    speaker: 'Merlin',
    text: "Les corbeaux tournent sur Logres, mauvais présage. Consulteras-tu les augures païens ?",
    left: { label: 'Consulter', effects: { magie: +6, foi: -6 } },
    right: { label: 'Prier Dieu', effects: { foi: +6, magie: -6 } },
    weight: 1,
  },
  {
    id: 'chute.lancelot.retour',
    era: 'chute',
    speaker: 'Lancelot',
    text: "Tu m'as banni, et tu avais raison. Mais Logres brûle, et mon épée est toujours tienne. Me rendras-tu ma place ?",
    unique: true,
    requires: { allFlags: ['lancelot.banni'] },
    left: {
      label: 'Reviens, mon frère',
      effects: { chevalerie: +9, couronne: -4 },
    },
    right: {
      label: 'Le ban est le ban',
      effects: { couronne: +4, chevalerie: -8 },
    },
    weight: 3,
  },
  {
    id: 'chute.guenievre.bucher',
    era: 'chute',
    speaker: "L'Évêque",
    text: "La reine adultère doit brûler — la loi de Dieu est claire, Sire. À moins que ton cœur, ou l'épée d'un banni, n'en décide autrement.",
    unique: true,
    requires: { allFlags: ['lancelot.banni'], gauge: { foi: [55, 100] } },
    left: {
      label: 'Le bûcher',
      effects: { foi: +10, chevalerie: -12, couronne: +2 },
      flags: ['guenievre.brulee'],
    },
    right: {
      label: "Qu'on la sauve",
      effects: { chevalerie: +6, couronne: -4, foi: -10 },
      flags: ['guenievre.sauvee'],
    },
    weight: 2,
  },
  {
    id: 'chute.guenievre.couvent',
    era: 'chute',
    speaker: 'Guenièvre',
    text: "Je pars pour le couvent d'Amesbury, mon roi. Prier pour Logres — et pour nous. Me retiendras-tu, cette fois ?",
    unique: true,
    requires: { noneFlags: ['guenievre.brulee'] },
    left: {
      label: 'La laisser partir',
      effects: { foi: +6, couronne: -4 },
    },
    right: {
      label: 'Reste, ma reine',
      effects: { couronne: +4, foi: -5 },
    },
    weight: 2,
  },
  {
    id: 'chute.fourreau.vole',
    era: 'chute',
    speaker: 'Un écuyer',
    text: "Sire… le Fourreau a disparu de tes appartements. On a vu une silhouette de femme quitter le château à l'aube.",
    unique: true,
    requires: { allFlags: ['relique.fourreau'], noneFlags: ['fourreau.perdu'] },
    left: {
      label: 'Traquer la voleuse',
      effects: { chevalerie: +4, magie: -8 },
      flags: ['fourreau.perdu'],
    },
    right: {
      label: 'Mon bras me protègera',
      effects: { couronne: +3, chevalerie: -4 },
      flags: ['fourreau.perdu'],
    },
    weight: 2,
  },
  {
    id: 'chute.famine.guerre',
    era: 'chute',
    speaker: 'Un paysan',
    text: "La guerre a mangé les récoltes, Sire. L'hiver mangera les enfants. Ouvriras-tu les greniers de l'armée ?",
    left: {
      label: 'Ouvrir les greniers',
      effects: { couronne: +6, chevalerie: -6 },
    },
    right: {
      label: "L'armée d'abord",
      effects: { chevalerie: +5, couronne: -7 },
    },
    weight: 1,
  },
  {
    id: 'chute.camlann.duel',
    era: ['chute', 'avalon'],
    speaker: 'Bédivère',
    text: "Face à face, enfin : toi et Mordred, au milieu des morts de Camlann. Une dernière charge, Sire. Lève Excalibur.",
    unique: true,
    requires: { allFlags: ['camlann'] },
    left: {
      label: 'Charger Mordred',
      effects: { chevalerie: -30, couronne: +4 },
    },
    right: {
      label: 'Tenter de le raisonner',
      effects: { couronne: -12, foi: +4, magie: -6 },
    },
    weight: 4,
  },
  {
    id: 'chute.sans.fourreau',
    era: 'chute',
    speaker: 'Bédivère',
    text: "Depuis que le Fourreau t'a quitté, tu portes la main à ton flanc à chaque ombre, Sire. Un roi sans protection doit-il mener la charge — ou la commander de loin ?",
    unique: true,
    requires: { allFlags: ['fourreau.perdu'] },
    left: {
      label: 'Mener la charge',
      effects: { chevalerie: +6, couronne: +2 },
    },
    right: {
      label: 'Commander de loin',
      effects: { couronne: +4, chevalerie: -5 },
    },
    weight: 1,
  },
  // ---- Standalone : guerre civile, famine, loyautés qui vacillent ----
  {
    id: 'chute.barons.defection',
    era: 'chute',
    speaker: 'Un conseiller',
    text: "Trois barons soupent avec tes ennemis, Sire — en secret, c'est-à-dire que tout le monde le sait. Les pendre coûte des alliés ; les racheter coûte de l'or.",
    left: { label: 'Les pendre haut', effects: { couronne: +6, chevalerie: -5 } },
    right: { label: 'Racheter leur foi', effects: { chevalerie: +4, couronne: -6 } },
    weight: 1,
  },
  {
    id: 'chute.saxons.profitent',
    era: 'chute',
    speaker: 'Un émissaire saxon',
    text: "Mon roi te propose un marché, Sire : il tient tes côtes pendant que tu fais ta guerre, et tu lui laisses ce qu'il tient déjà. Chacun sa guerre.",
    left: { label: 'Chasser les Saxons', effects: { chevalerie: +6, couronne: -6 } },
    right: { label: 'Accepter le marché', effects: { couronne: +5, chevalerie: -7 } },
    weight: 1,
  },
  {
    id: 'chute.presage.eclipse',
    era: 'chute',
    speaker: 'Merlin',
    text: "Le soleil s'est voilé en plein midi et l'armée y lit ta mort, Sire. Je peux leur lire autre chose dans le ciel — c'est mon métier.",
    left: { label: 'Écouter le présage', effects: { magie: +6, foi: -6 } },
    right: { label: 'Dieu seul décide', effects: { foi: +5, magie: -6 } },
    weight: 1,
  },
  {
    id: 'chute.deserteurs.pendaison',
    era: 'chute',
    speaker: 'Un baron',
    text: "On a repris douze déserteurs, Sire. La corde en ferait des exemples ; la clémence en ferait des soldats. Les deux se plaident.",
    left: { label: 'La corde', effects: { couronne: +6, chevalerie: -6 } },
    right: { label: 'La clémence', effects: { chevalerie: +5, couronne: -5 } },
    weight: 1,
  },
  {
    id: 'chute.famine.greniers',
    era: 'chute',
    speaker: 'Un paysan',
    text: "L'Église a du grain plein ses celliers, Sire, et nous des enfants creux. L'évêque dit que c'est le grain de Dieu. Dieu mange peu, pourtant.",
    left: { label: "Ouvrir les celliers d'Église", effects: { couronne: +6, foi: -7 } },
    right: { label: "Le bien d'Église est sacré", effects: { foi: +6, couronne: -6 } },
    weight: 1,
  },
  {
    id: 'chute.gauvain.vengeance',
    era: 'chute',
    speaker: 'Gauvain',
    text: "Ils ont tué mon frère, Sire. Je veux la tête du meurtrier, fût-elle au bout d'une guerre de plus. Tu me la dois — l'honneur me la doit.",
    left: { label: 'Venger son frère', effects: { chevalerie: +7, couronne: -6 } },
    right: { label: 'Assez de guerres', effects: { couronne: +5, chevalerie: -6 } },
    weight: 1,
  },
  {
    id: 'chute.merlin.ombre',
    era: 'chute',
    speaker: 'Un écuyer',
    text: "Une voix dans la brume, Sire — on jurerait Merlin. Elle murmure des chemins pour sauver Logres. Les brumes mentent, parfois. Parfois non.",
    left: { label: 'Suivre la voix', effects: { magie: +7, foi: -6 } },
    right: { label: 'Ignorer la brume', effects: { foi: +5, magie: -6 } },
    weight: 1,
  },
  {
    id: 'chute.tresor.fondre',
    era: 'chute',
    speaker: 'Keu',
    text: "Les soldats veulent leur solde, Sire, et les coffres sont vides. Reste la vaisselle sacrée. Elle brille beaucoup, pour des gens qui prêchent la pauvreté.",
    left: { label: 'Fondre la vaisselle', effects: { couronne: +7, foi: -8 } },
    right: { label: 'Toucher à Dieu, jamais', effects: { foi: +6, couronne: -6 } },
    weight: 1,
  },
  {
    id: 'chute.ecuyer.trahison',
    era: 'chute',
    speaker: 'Un écuyer',
    text: "Je sais qui ouvre tes portes à l'ennemi, Sire. Son nom contre un titre — un petit titre. La loyauté a ses prix, par les temps qui courent.",
    left: { label: 'Payer le titre', effects: { couronne: +6, chevalerie: -5 } },
    right: { label: 'On ne marchande pas', effects: { chevalerie: +4, couronne: -5 } },
    weight: 1,
  },
  {
    id: 'chute.paix.honteuse',
    era: 'chute',
    speaker: 'Un conseiller',
    text: "L'ennemi offre la paix, Sire — contre la province de l'ouest. Une paix de boutiquier, mais une paix. Les morts, eux, ne cultivent rien.",
    left: { label: 'Céder la province', effects: { couronne: +5, chevalerie: -7 } },
    right: { label: 'Plutôt la guerre', effects: { chevalerie: +6, couronne: -6 } },
    weight: 1,
  },
  {
    id: 'chute.eveque.excommunie',
    era: 'chute',
    speaker: "L'Évêque",
    text: "Ton allié des marches vit dans le péché et s'en vante, Sire. Je vais l'excommunier — sauf si son roi me convainc que Dieu peut attendre la fin de la guerre.",
    left: { label: "Qu'il soit excommunié", effects: { foi: +7, couronne: -6 } },
    right: { label: 'Dieu attendra', effects: { couronne: +5, foi: -7 } },
    weight: 1,
  },
  {
    id: 'chute.pillards.propres',
    era: 'chute',
    speaker: 'Un paysan',
    text: "Tes propres soldats ont vidé nos granges et brûlé le moulin, Sire. On nous avait dit que c'étaient les autres, les pillards.",
    left: { label: 'Pendre les coupables', effects: { chevalerie: +6, couronne: -5 } },
    right: { label: 'La guerre excuse tout', effects: { couronne: +4, chevalerie: -7 } },
    weight: 1,
  },
  {
    id: 'chute.bedivere.conseil',
    era: 'chute',
    speaker: 'Bédivère',
    text: "Il est encore temps de négocier, Sire. Dans un mois, il ne restera plus rien à offrir — ni personne pour signer.",
    left: { label: 'Négocier', effects: { couronne: +5, chevalerie: -5 } },
    right: { label: "Tenir jusqu'au bout", effects: { chevalerie: +6, couronne: -5 } },
    weight: 1,
  },
  {
    id: 'chute.sorts.derniers',
    era: 'chute',
    speaker: 'Une fée',
    text: "Une victoire, roi de Logres — une seule, entière, éclatante. Il ne t'en coûtera qu'une âme. Je ne dis pas laquelle, c'est la surprise.",
    left: { label: 'Payer le sort', effects: { magie: +8, foi: -8 } },
    right: { label: 'Garder son âme', effects: { foi: +7, magie: -7 } },
    weight: 1,
  },
];

export const avalon = [
  {
    id: 'avalon.barque',
    era: 'avalon',
    speaker: 'Morgane',
    text: "Tu es blessé à mort, frère. Une barque attend pour te porter à Avalon. Y monteras-tu ?",
    unique: true,
    left: {
      label: 'Monter dans la barque',
      effects: { magie: +10, foi: -6 },
    },
    right: {
      label: 'Mourir en roi chrétien',
      effects: { foi: +10, magie: -8 },
    },
    weight: 3,
  },
  {
    id: 'avalon.filler.excalibur',
    era: 'avalon',
    filler: true,
    speaker: 'Un chevalier',
    text: "Faut-il rendre Excalibur au lac, comme le veut la légende ?",
    left: { label: 'La rendre au lac', effects: { magie: +7, chevalerie: -5 } },
    right: { label: 'La garder', effects: { chevalerie: +6, magie: -6 } },
    weight: 1,
  },
  {
    id: 'avalon.filler.memoire',
    era: 'avalon',
    filler: true,
    speaker: 'Le peuple',
    text: "On grave déjà ta légende dans la pierre. La veux-tu sincère, ou flatteuse ?",
    left: { label: 'Sincère', effects: { foi: +5, couronne: -3 } },
    right: { label: 'Flatteuse', effects: { couronne: +6, foi: -4 } },
    weight: 1,
  },
  {
    id: 'avalon.bedivere',
    era: 'avalon',
    speaker: 'Bédivère',
    text: "Deux fois tu m'as ordonné de jeter Excalibur au lac, deux fois j'ai menti. Elle est trop belle, Sire. Ordonne encore ?",
    unique: true,
    requires: { allFlags: ['relique.excalibur'], noneFlags: ['excalibur.rendue'] },
    left: {
      label: 'Jette-la, Bédivère',
      effects: { magie: +8, chevalerie: -4 },
      flags: ['excalibur.rendue'],
    },
    right: {
      label: "Garde-la pour Logres",
      effects: { chevalerie: +5, magie: -6 },
    },
    weight: 3,
  },
  {
    id: 'avalon.moines',
    era: 'avalon',
    speaker: 'Un moine',
    text: "Glastonbury réclame ta dépouille, Sire — un tombeau chrétien, des pèlerins, des siècles de prières. Avalon peut attendre.",
    unique: true,
    left: {
      label: 'Un tombeau chrétien',
      effects: { foi: +7, magie: -6 },
    },
    right: {
      label: "J'appartiens à Avalon",
      effects: { magie: +6, foi: -6 },
    },
    weight: 1,
  },
  {
    id: 'avalon.roi.futur',
    era: 'avalon',
    speaker: 'Merlin',
    text: "On écrira : « le roi de jadis et de demain ». Veux-tu que Logres t'attende — ou qu'elle apprenne à vivre sans toi ?",
    unique: true,
    left: {
      label: "Je reviendrai",
      effects: { magie: +6, couronne: +3, foi: -5 },
    },
    right: {
      label: "Qu'elle vive sans moi",
      effects: { foi: +5, couronne: -4 },
    },
    weight: 2,
  },
  // ---- Standalone : adieux, mémoire, ce que Logres retiendra ----
  {
    id: 'avalon.dame.adieu',
    era: 'avalon',
    speaker: 'La Dame du Lac',
    text: "Il est l'heure de rendre ce qu'Avalon t'a prêté, roi de Logres. L'épée, le fourreau, la gloire. Les rendras-tu en paix ?",
    unique: true,
    left: { label: 'Rendre les dons', effects: { magie: +7, chevalerie: -5 } },
    right: { label: "S'y accrocher", effects: { chevalerie: +5, magie: -6 } },
    weight: 1,
  },
  {
    id: 'avalon.confession',
    era: 'avalon',
    speaker: 'Un moine',
    text: "L'heure des comptes, Sire. Confesse Morgane, l'enfant, la nuit d'antan — ou emporte ton secret sous la pierre.",
    unique: true,
    left: { label: 'Tout confesser', effects: { foi: +7, magie: -6 } },
    right: { label: 'Emporter le secret', effects: { magie: +5, foi: -6 } },
    weight: 1,
  },
  {
    id: 'avalon.barde.legende',
    era: 'avalon',
    speaker: 'Un barde',
    text: "Donne-moi ta vraie fin, Sire, et je la chanterai mille ans. Ou donne-m'en une belle — ça se chante mieux.",
    unique: true,
    left: { label: 'La vérité', effects: { foi: +6, couronne: -4 } },
    right: { label: 'La légende', effects: { couronne: +6, foi: -4 } },
    weight: 1,
  },
  {
    id: 'avalon.heritier.dernier',
    era: 'avalon',
    speaker: 'Bédivère',
    text: "D'un souffle, Sire : qui portera Logres ? Un nom, et je le porterai plus loin que Camlann.",
    unique: true,
    left: { label: 'Nommer un héritier', effects: { couronne: +6, chevalerie: -4 } },
    right: { label: 'Logres choisira seule', effects: { chevalerie: +5, couronne: -5 } },
    weight: 1,
  },
  {
    id: 'avalon.merlin.prophetie',
    era: 'avalon',
    speaker: 'Merlin',
    text: "On écrira que tu reviendras au besoin de la Bretagne. Y croiras-tu toi-même — c'est toute la question.",
    unique: true,
    left: { label: "J'y crois", effects: { magie: +7, foi: -5 } },
    right: { label: 'Nul ne revient', effects: { foi: +6, magie: -6 } },
    weight: 1,
  },
  {
    id: 'avalon.peuple.tombeau',
    era: 'avalon',
    speaker: 'Le peuple',
    text: "Laisse-nous un tombeau, Sire — une pierre où pleurer. Ou disparais dans la brume, et laisse-nous le doute.",
    unique: true,
    left: { label: 'Une pierre où pleurer', effects: { foi: +6, magie: -5 } },
    right: { label: 'La brume et le doute', effects: { magie: +6, foi: -5 } },
    weight: 1,
  },
  {
    id: 'avalon.ermite.pardon',
    era: 'avalon',
    speaker: 'Un ermite',
    text: "Pardonne à Mordred, Sire, même mort — surtout mort. Un roi qui pardonne entre plus léger dans la légende.",
    unique: true,
    left: { label: 'Pardonner à mon fils', effects: { foi: +7, couronne: -4 } },
    right: { label: 'Jamais', effects: { couronne: +5, foi: -6 } },
    weight: 1,
  },
  {
    id: 'avalon.brume.avalon',
    era: 'avalon',
    speaker: 'Morgane',
    text: "La brume se lève, frère. Devant : Avalon et ses pommiers. Derrière : Logres, une dernière fois. Où porteras-tu les yeux ?",
    unique: true,
    left: { label: 'Traverser la brume', effects: { magie: +7, foi: -5 } },
    right: { label: 'Regarder Logres', effects: { foi: +6, magie: -5 } },
    weight: 1,
  },
];
