// Ère 1 — L'Épée dans la Roche. Ascension d'Arthur, légitimité fragile.
// Format de carte : voir docs/DESIGN.md §3.

export const roche = [
  {
    id: 'roche.merlin.couronne',
    era: 'roche',
    speaker: 'Merlin',
    text: "L'épée a quitté la pierre dans ta main. Proclameras-tu ton droit divin, ou laisseras-tu les barons t'élire ?",
    left: {
      label: 'Droit divin',
      effects: { foi: +8, couronne: +6, chevalerie: -6 },
    },
    right: {
      label: 'Les barons voteront',
      effects: { couronne: +8, chevalerie: +6, magie: -6 },
    },
    weight: 3,
  },
  {
    id: 'roche.eveque.paien',
    era: 'roche',
    speaker: "L'Évêque",
    text: "Le vieux Merlin murmure à ton oreille des sorts païens, mon roi. L'Église exige que tu le chasses de la cour.",
    left: {
      label: 'Chasser Merlin',
      effects: { foi: +12, magie: -14 },
      flags: ['merlin.offense'],
    },
    right: {
      label: 'Merlin reste',
      effects: { magie: +10, foi: -10 },
    },
    weight: 2,
  },
  {
    id: 'roche.dame.lac',
    era: 'roche',
    speaker: 'La Dame du Lac',
    text: "Ton épée s'est brisée. Je puis t'en offrir une forgée à Avalon — Excalibur. Accepteras-tu ce présent des fées ?",
    unique: true,
    left: {
      label: 'Accepter Excalibur',
      effects: { magie: +10, chevalerie: +8 },
      flags: ['relique.excalibur'],
    },
    right: {
      label: 'Refuser le sortilège',
      effects: { foi: +8, chevalerie: -4 },
    },
    weight: 2,
  },
  // ---- Chaîne : la naissance de Mordred (posée tôt, éclatera à l'ère de la Chute) ----
  {
    id: 'roche.morgane.nuit',
    era: 'roche',
    speaker: 'Morgane',
    text: "La nuit est froide, mon roi, et je ne suis pas si lointaine parente. M'ouvriras-tu ta porte ?",
    unique: true,
    requires: { noneFlags: ['lignee.morgane'] }, // la Reine-Fée ne se croise pas elle-même
    left: {
      label: 'Ouvrir la porte',
      effects: { magie: +8, foi: -8 },
      flags: ['mordred.concu'],
    },
    right: {
      label: 'La renvoyer',
      effects: { foi: +6, magie: -6 },
    },
    weight: 1,
  },
  // ---- Cartes de remplissage (toujours éligibles) : garantissent le non-blocage ----
  {
    id: 'roche.filler.impots',
    era: 'roche',
    filler: true,
    speaker: 'Keu',
    text: "Les coffres de la couronne sonnent creux. Lèverai-je un nouvel impôt sur les récoltes ?",
    left: { label: 'Lever l’impôt', effects: { couronne: +6, chevalerie: +4 } },
    right: { label: 'Épargner le peuple', effects: { couronne: -4, foi: +5 } },
    weight: 1,
  },
  {
    id: 'roche.filler.tournoi',
    era: 'roche',
    filler: true,
    speaker: 'Un héraut',
    text: "Un tournoi rassemblerait les chevaliers errants sous ta bannière. En ordonnes-tu un ?",
    left: { label: 'Grand tournoi', effects: { chevalerie: +7, couronne: -3 } },
    right: { label: 'Trop coûteux', effects: { couronne: +4, chevalerie: -4 } },
    weight: 1,
  },
  {
    id: 'roche.uther.doute',
    era: 'roche',
    speaker: 'Un baron',
    text: "On murmure que tu n'es pas le fils d'Uther, mais un bâtard placé là par le sorcier. Feras-tu taire la rumeur ?",
    unique: true,
    left: {
      label: 'Punir les médisants',
      effects: { couronne: +6, chevalerie: -5 },
    },
    right: {
      label: 'Que Merlin témoigne',
      effects: { magie: +7, couronne: -3, foi: -3 },
    },
    weight: 2,
  },
  {
    id: 'roche.lot.defi',
    era: 'roche',
    speaker: 'Le roi Lot',
    text: "Un garçon sorti d'une pierre ne régnera pas sur moi. Orcanie se soulève — à moins que tu n'achètes ma loyauté.",
    unique: true,
    left: {
      label: 'La guerre, donc',
      effects: { chevalerie: +8, couronne: -6 },
    },
    right: {
      label: 'Négocier son allégeance',
      effects: { couronne: +6, chevalerie: -6 },
    },
    weight: 2,
  },
  {
    id: 'roche.fourreau',
    era: 'roche',
    speaker: 'La Dame du Lac',
    text: "L'épée tranche, mais le Fourreau garde. Tant que tu le porteras, ton sang ne coulera pas. Le veux-tu aussi ?",
    unique: true,
    requires: { allFlags: ['relique.excalibur'] },
    left: {
      label: 'Prendre le Fourreau',
      effects: { magie: +8, foi: -6 },
      flags: ['relique.fourreau'],
    },
    right: {
      label: "L'épée me suffit",
      effects: { chevalerie: +5, magie: -4 },
    },
    weight: 2,
  },
  {
    id: 'roche.saxons.fortins',
    era: 'roche',
    speaker: 'Gauvain',
    text: "Les Saxons tâtent nos côtes, Sire. Des fortins de bois sur les falaises les décourageraient — mais videraient tes coffres.",
    unique: true,
    left: {
      label: 'Bâtir les fortins',
      effects: { chevalerie: +6, couronne: -5 },
      flags: ['cote.fortifiee'],
    },
    right: {
      label: 'La mer nous garde',
      effects: { couronne: +4, chevalerie: -6 },
    },
    weight: 1,
  },
  {
    id: 'roche.fee.tribut',
    era: 'roche',
    speaker: 'Une fée',
    text: "Sous les anciens rois, le petit peuple recevait lait et miel à chaque lune. Le nouveau roi honorera-t-il l'usage ?",
    left: {
      label: "Honorer l'usage",
      effects: { magie: +7, foi: -6 },
    },
    right: {
      label: 'Les temps ont changé',
      effects: { foi: +6, magie: -7 },
    },
    weight: 1,
  },
  {
    id: 'roche.keu.charge',
    era: 'roche',
    speaker: 'Keu',
    text: "Je t'ai vu grandir, je t'ai servi avant la pierre. La charge de sénéchal me revient, frère — dis que non pour voir.",
    unique: true,
    left: {
      label: 'Nommer Keu sénéchal',
      effects: { couronne: +4, chevalerie: -3 },
    },
    right: {
      label: 'Le mérite décidera',
      effects: { chevalerie: +5, couronne: -4 },
    },
    weight: 1,
  },
  {
    id: 'roche.couronnement',
    era: 'roche',
    speaker: "L'Évêque",
    text: "Le peuple doit voir Dieu poser la couronne sur ta tête. Un sacre fastueux, en grande cathédrale — et à grands frais.",
    unique: true,
    left: {
      label: 'Sacre fastueux',
      effects: { foi: +7, couronne: +4, magie: -6 },
    },
    right: {
      label: "L'épée m'a déjà sacré",
      effects: { magie: +6, couronne: -3, foi: -5 },
    },
    weight: 2,
  },
  {
    id: 'roche.pelerin.pierre',
    era: 'roche',
    speaker: 'Un pèlerin',
    text: "Des foules viennent toucher la pierre fendue, Sire. Faut-il en faire un sanctuaire… et y poster un percepteur ?",
    left: {
      label: 'Sanctuaire payant',
      effects: { couronne: +5, foi: -4 },
    },
    right: {
      label: 'La pierre reste libre',
      effects: { foi: +5, couronne: -3 },
    },
    weight: 1,
  },
  // ---- Cartes standalone (Task 6) : matière de deck, roster fermé ----
  {
    id: 'roche.bandits.route',
    era: 'roche',
    speaker: 'Un marchand',
    text: "Des brigands rançonnent la route du sel, Sire, et mes bourses avec. Enverras-tu tes chevaliers nettoyer les bois, ou me faut-il payer les loups ?",
    left: { label: 'Nettoyer les bois', effects: { chevalerie: +6, couronne: -4 } },
    right: { label: 'Débrouille-toi', effects: { couronne: +4, chevalerie: -4 } },
    weight: 1,
  },
  {
    id: 'roche.baron.hommage',
    era: 'roche',
    speaker: 'Un baron',
    text: "Un roi tiré d'un caillou ne fait pas la loi chez moi, tonne-t-il devant toute la cour assemblée. Le forceras-tu à plier le genou, ou lui laisseras-tu ses terres en paix ?",
    left: { label: "Forcer l'hommage", effects: { couronne: +6, chevalerie: -4 } },
    right: { label: 'Le laisser en paix', effects: { chevalerie: +5, couronne: -5 } },
    weight: 1,
  },
  {
    id: 'roche.moine.ecole',
    era: 'roche',
    speaker: 'Un moine',
    text: "Un moine gratte à la porte du palais : il veut fonder une école de copistes, pour que les mots de Dieu — et les tiens — ne meurent pas avec leurs auteurs. Financeras-tu son encre ?",
    unique: true,
    left: { label: "Financer l'école", effects: { foi: +6, couronne: -5 } },
    right: { label: 'Les coffres sont vides', effects: { couronne: +4, foi: -5 } },
    weight: 1,
  },
  {
    id: 'roche.fee.moisson',
    era: 'roche',
    speaker: 'Une fée',
    text: "Une fée aux pieds nus promet des moissons grasses jusqu'à la neige — si tes villages dansent une nuit entière sous la lune, comme au temps d'avant l'Église. Acceptes-tu ce marché ?",
    left: { label: 'Accepter la danse', effects: { magie: +7, foi: -6 } },
    right: { label: 'Refuser le paganisme', effects: { foi: +6, magie: -6 } },
    weight: 1,
  },
  {
    id: 'roche.saxons.otage',
    era: 'roche',
    speaker: 'Un émissaire saxon',
    text: "Les Saxons te rendent ton neveu captif, Sire, sain et sauf — contre un tribut qui sentira la reddition dans toutes les cours d'Europe. Payeras-tu ce prix ?",
    unique: true,
    left: { label: 'Payer le tribut', effects: { chevalerie: +4, couronne: -6 } },
    right: { label: 'Le libérer par les armes', effects: { couronne: +5, chevalerie: -5 } },
    weight: 1,
  },
  {
    id: 'roche.relique.os',
    era: 'roche',
    speaker: "L'Évêque",
    text: "L'Évêque brandit un coffret d'ossements jaunis : les reliques d'un saint local, dit-il, guérisseuses d'écrouelles. Toi seul sais qu'un berger a perdu un mouton la semaine passée. Les authentifies-tu devant la cour ?",
    unique: true,
    left: { label: 'Authentifier les reliques', effects: { foi: +7, magie: -5 } },
    right: { label: 'Douter en silence', effects: { magie: +5, foi: -6 } },
    weight: 1,
  },
  {
    id: 'roche.duel.judiciaire',
    era: 'roche',
    speaker: 'Gauvain',
    text: "Deux barons réclament un duel judiciaire pour une lisière de terre, Sire. Gauvain propose d'arbitrer lui-même l'affaire — ou trancheras-tu par décret, au risque de passer pour un tyran ?",
    unique: true,
    left: { label: 'Laisser Gauvain arbitrer', effects: { chevalerie: +6, couronne: -4 } },
    right: { label: 'Trancher par décret', effects: { couronne: +5, chevalerie: -5 } },
    weight: 1,
  },
  {
    id: 'roche.sorciere.puits',
    era: 'roche',
    speaker: 'Un paysan',
    text: "Le puits du village s'est tari net, et le peuple jure qu'une vieille recluse y a jeté un sort. Ils veulent la noyer pour en être sûrs. La leur laisses-tu ?",
    left: { label: 'La laisser au peuple', effects: { foi: +6, magie: -5 }, flags: [['cruaute', 1]] },
    right: { label: 'La protéger', effects: { magie: +5, foi: -6 } },
    weight: 1,
  },
  {
    id: 'roche.lot.mariage',
    era: 'roche',
    speaker: 'Le roi Lot',
    text: "Le roi Lot t'offre la paix d'Orcanie — contre la main d'une de tes proches pour son fils, un promis qu'on dit brutal. Scelles-tu cette alliance de sang ?",
    unique: true,
    left: { label: 'Sceller le mariage', effects: { couronne: +6, chevalerie: -4 } },
    right: { label: "Refuser, préparer l'épée", effects: { chevalerie: +6, couronne: -5 } },
    weight: 1,
  },
  {
    id: 'roche.forge.epees',
    era: 'roche',
    speaker: 'Keu',
    text: "Keu t'amène un forgeron saxon rallié à ta cause : ses lames, dit-il, tranchent mieux que tout l'acier breton. Les chevaliers murmurent qu'un fer d'ennemi porte malheur. L'accueilles-tu à la forge royale ?",
    unique: true,
    left: { label: 'Accueillir le forgeron', effects: { chevalerie: +6, foi: -4 } },
    right: { label: 'Le renvoyer', effects: { foi: +5, chevalerie: -5 } },
    weight: 1,
  },
  {
    id: 'roche.recolte.dime',
    era: 'roche',
    speaker: 'Un pèlerin',
    text: "Un pèlerin au ventre creux s'arrête devant ton trône : l'année fut maigre, dit-il, et la dîme de l'Église vide les greniers avant l'hiver. Maintiens-tu l'impôt sacré ?",
    left: { label: 'Maintenir la dîme', effects: { foi: +6, couronne: -4 } },
    right: { label: 'Soulager les greniers', effects: { couronne: +5, foi: -6 } },
    weight: 1,
  },
  {
    id: 'roche.chasse.blanche',
    era: 'roche',
    speaker: 'Un héraut',
    text: "Un cerf d'un blanc immaculé a traversé la lande sous les yeux de toute la cour — présage féerique, murmure-t-on déjà. Ordonnes-tu la chasse, ou proclames-tu une fête en son honneur ?",
    unique: true,
    left: { label: 'Ordonner la chasse', effects: { magie: -6, couronne: +4 } },
    right: { label: "L'honorer par une fête", effects: { magie: +6, couronne: -5 } },
    weight: 1,
  },

  // ---- Identité de lignée : chaque roi est le héros de SA légende ----
  {
    id: 'roche.arthur.epee',
    era: 'roche',
    speaker: 'Le peuple',
    text: "C'est toi qui as tiré l'épée, Sire — pas un baron, pas un géant : toi. Alors dis-nous : le fils de personne devenu roi, c'était le plan de Dieu, ou celui de Merlin ?",
    unique: true,
    requires: { allFlags: ['lignee.arthur'] },
    left: { label: 'Le plan de Dieu', effects: { foi: +6, magie: -4 } },
    right: { label: 'Celui de Merlin', effects: { magie: +6, foi: -5 } },
    weight: 2,
  },
  {
    id: 'roche.arthur.keu',
    era: 'roche',
    speaker: 'Keu',
    text: "J'étais ton aîné, Arthur — pardon : Sire. Je t'ai vu rater tes gammes à l'épée. Fais de moi ton sénéchal, qu'au moins la cuisine soit bien gardée.",
    unique: true,
    requires: { allFlags: ['lignee.arthur'] },
    left: { label: 'Sénéchal, mon frère', effects: { chevalerie: +5, couronne: -3 } },
    right: { label: 'Que chacun fasse ses preuves', effects: { couronne: +4, chevalerie: -4 } },
    weight: 2,
  },
  {
    id: 'roche.uther.tribut',
    era: 'roche',
    speaker: 'Un baron',
    text: "Nous n'avons pas oublié ce que tu fais aux châteaux qui ferment leurs portes, Uther. Voici l'or. Inutile de compter.",
    unique: true,
    requires: { allFlags: ['lignee.uther'] },
    left: { label: "Prendre l'or en souriant", effects: { couronne: +6, chevalerie: -4 } },
    right: { label: "Rendre l'or, exiger l'amitié", effects: { chevalerie: +5, couronne: -4 } },
    weight: 2,
  },
  {
    id: 'roche.uther.dette',
    era: 'roche',
    speaker: 'Merlin',
    text: "Tintagel, la tempête, le visage d'un autre… Tu te souviens du prix, Uther Pendragon. Je ne l'ai pas encore réclamé. Dors bien.",
    unique: true,
    requires: { allFlags: ['lignee.uther'] },
    left: {
      label: "Honorer la dette, quelle qu'elle soit",
      effects: { magie: +6, couronne: -5 },
      flags: ['dette.assumee'],
    },
    right: {
      label: 'Les dettes meurent avec les mages',
      effects: { couronne: +4, magie: -6 },
      flags: ['dette.reniee'],
    },
    weight: 2,
  },
  {
    id: 'roche.constantin.sacre',
    era: 'roche',
    speaker: "L'Évêque",
    text: "Rome te proclame « roi très chrétien », Sire — l'Église te sacre, te bénit, te garde. Il n'y a presque rien à signer.",
    unique: true,
    requires: { allFlags: ['lignee.constantin'] },
    left: { label: 'Accepter le sacre de Rome', effects: { foi: +7, couronne: -5 } },
    right: { label: 'Roi par le sang, pas par Rome', effects: { couronne: +5, foi: -6 } },
    weight: 2,
  },
  {
    id: 'roche.constantin.bosquet',
    era: 'roche',
    speaker: 'Une fée',
    text: "Ton dieu chasse les nôtres des bois, roi qui prie. Laisse-nous un bosquet — un seul — et les racines se souviendront de toi.",
    unique: true,
    requires: { allFlags: ['lignee.constantin'] },
    left: { label: 'Un bosquet pour les fées', effects: { magie: +6, foi: -5 } },
    right: { label: 'Un seul Dieu, partout', effects: { foi: +6, magie: -6 } },
    weight: 2,
  },
  {
    id: 'roche.morgane.sacre',
    era: 'roche',
    speaker: "L'Évêque",
    text: "L'Église ne posera pas de couronne sur une tête de fée, Madame. Trouve un autre dieu pour te sacrer — il paraît que tu en connais.",
    unique: true,
    requires: { allFlags: ['lignee.morgane'] },
    left: { label: 'Sacrée par la Dame du Lac', effects: { magie: +7, foi: -6 } },
    right: { label: "Plier l'Église par la loi", effects: { couronne: +5, foi: -4 } },
    weight: 3,
  },
  {
    id: 'roche.morgane.soeur',
    era: 'roche',
    speaker: 'La Dame du Lac',
    text: "Une sœur d'Avalon sur un trône d'hommes, quelle idée. Reviens quand tu veux, ma sœur — les pommiers, eux, ne complotent pas.",
    unique: true,
    requires: { allFlags: ['lignee.morgane'] },
    left: {
      label: 'Ma place est ici',
      effects: { couronne: +5, magie: -4 },
      flags: ['avalon.refuse'],
    },
    right: {
      label: 'Un pied dans chaque monde',
      effects: { magie: +6, couronne: -4 },
      flags: ['avalon.lien'],
    },
    weight: 2,
  },
];
